name: PR Cargo Preflight Checks

on:
    pull_request:
        branches:
            - master
    push:
        branches:
            - master

jobs:
    checks:
        name: Cargo
        uses: ./.github/workflows/checks.yml
